server:
  port: 8082

spring:
  application:
    name: VACCINATION-CENTRE
  datasource:
    url: jdbc:mysql://localhost:3306/vaccinationcentre
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  cloud:
    gateway:
      routes:
      - id: VACCINATION-CENTER-SERVICE
        uri: lb://VACCINATION-CENTER
        predicates:
        - Path=/vaccinationcenter/**
